### ISSUE TITLE
coordinates.cluster_assign_centers() doesn't work and isn't tested

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#230]
```python
X = np.random.rand(100,2)
centers = np.array([[-0.5,0],[0.5,0]])
coor.cluster_assign_centers(data=X, centers=centers)
```

leads to:
```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-ad1f5ec290af> in <module>()
      1 X = np.random.rand(100,2)
      2 centers = np.array([[-0.5,0],[0.5,0]])
----> 3 coor.cluster_assign_centers(data=X, centers=centers)

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/api.pyc in cluster_assign_centers(data, centers, stride)
    941                          ' or NumPy array')
    942     res = _AssignCenters(centers)
--> 943     return _param_stage(data, res, stride=stride)

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/api.pyc in _param_stage(previous_stage, this_stage, stride)
    585     this_stage.data_producer = inputstage
    586     this_stage.chunksize = inputstage.chunksize
--> 587     this_stage.parametrize(stride=stride)
    588     return this_stage
    589 

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in parametrize(self, stride)
    234                     # first chunk
    235                     return_value = self._param_add_data(
--> 236                         X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y=Y, stride=stride)
    237                     if isinstance(return_value, tuple):
    238                         add_data_finished, lag = return_value

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/assign.pyc in _param_add_data(self, X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y, stride)
     45         if t == 0:
     46             n = self.data_producer.trajectory_length(itraj, stride=stride)
---> 47             self.dtrajs.append(np.empty(n, dtype=int))
     48 
     49         L = np.shape(X)[0]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in dtrajs(self)
     29     def dtrajs(self):
     30         if (len(self._dtrajs) == 0):  # nothing assigned yet, doing that now
---> 31             return self.assign(stride = 1)
     32         else:
     33             return self._dtrajs  # returning what we have saved

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in assign(self, X, stride)
     80         if X is None:
     81             # map to column vectors
---> 82             mapped = self.get_output(stride=stride)
     83             # flatten and save
     84             self._dtrajs = [np.transpose(m)[0] for m in mapped]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in get_output(self, dimensions, stride)
    523         last_itraj = -1
    524         t = 0  # first time point
--> 525         for itraj, chunk in self.iterator(stride=stride):
    526             if itraj != last_itraj:
    527                 last_itraj = itraj

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in iterator(self, stride, lag)
    455             data.
    456         """
--> 457         self._reset(stride=stride)
    458         return TransformerIterator(self, stride=stride, lag=lag)
    459 

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in _reset(self, stride)
    345         """_reset data position"""
    346         if not self._parametrized:  # TODO: should this stay or should it go?
--> 347             self.parametrize()
    348         self._itraj = 0
    349         self._t = 0

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in parametrize(self, stride)
    234                     # first chunk
    235                     return_value = self._param_add_data(
--> 236                         X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y=Y, stride=stride)
    237                     if isinstance(return_value, tuple):
    238                         add_data_finished, lag = return_value

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/assign.pyc in _param_add_data(self, X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y, stride)
     45         if t == 0:
     46             n = self.data_producer.trajectory_length(itraj, stride=stride)
---> 47             self.dtrajs.append(np.empty(n, dtype=int))
     48 
     49         L = np.shape(X)[0]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in dtrajs(self)
     29     def dtrajs(self):
     30         if (len(self._dtrajs) == 0):  # nothing assigned yet, doing that now
---> 31             return self.assign(stride = 1)
     32         else:
     33             return self._dtrajs  # returning what we have saved

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in assign(self, X, stride)
     80         if X is None:
     81             # map to column vectors
---> 82             mapped = self.get_output(stride=stride)
     83             # flatten and save
     84             self._dtrajs = [np.transpose(m)[0] for m in mapped]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in get_output(self, dimensions, stride)
    523         last_itraj = -1
    524         t = 0  # first time point
--> 525         for itraj, chunk in self.iterator(stride=stride):
    526             if itraj != last_itraj:
    527                 last_itraj = itraj

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in iterator(self, stride, lag)
    455             data.
    456         """
--> 457         self._reset(stride=stride)
    458         return TransformerIterator(self, stride=stride, lag=lag)
    459 

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in _reset(self, stride)
    345         """_reset data position"""
    346         if not self._parametrized:  # TODO: should this stay or should it go?
--> 347             self.parametrize()
    348         self._itraj = 0
    349         self._t = 0

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in parametrize(self, stride)
    234                     # first chunk
    235                     return_value = self._param_add_data(
--> 236                         X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y=Y, stride=stride)
    237                     if isinstance(return_value, tuple):
    238                         add_data_finished, lag = return_value

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/assign.pyc in _param_add_data(self, X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y, stride)
     45         if t == 0:
     46             n = self.data_producer.trajectory_length(itraj, stride=stride)
---> 47             self.dtrajs.append(np.empty(n, dtype=int))
     48 
     49         L = np.shape(X)[0]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in dtrajs(self)
     29     def dtrajs(self):
     30         if (len(self._dtrajs) == 0):  # nothing assigned yet, doing that now
---> 31             return self.assign(stride = 1)
     32         else:
     33             return self._dtrajs  # returning what we have saved

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in assign(self, X, stride)
     80         if X is None:
     81             # map to column vectors
---> 82             mapped = self.get_output(stride=stride)
     83             # flatten and save
     84             self._dtrajs = [np.transpose(m)[0] for m in mapped]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in get_output(self, dimensions, stride)
    523         last_itraj = -1
    524         t = 0  # first time point
--> 525         for itraj, chunk in self.iterator(stride=stride):
    526             if itraj != last_itraj:
    527                 last_itraj = itraj

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in iterator(self, stride, lag)
    455             data.
    456         """
--> 457         self._reset(stride=stride)
    458         return TransformerIterator(self, stride=stride, lag=lag)
    459 

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in _reset(self, stride)
    345         """_reset data position"""
    346         if not self._parametrized:  # TODO: should this stay or should it go?
--> 347             self.parametrize()
    348         self._itraj = 0
    349         self._t = 0

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in parametrize(self, stride)
    234                     # first chunk
    235                     return_value = self._param_add_data(
--> 236                         X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y=Y, stride=stride)
    237                     if isinstance(return_value, tuple):
    238                         add_data_finished, lag = return_value

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/assign.pyc in _param_add_data(self, X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y, stride)
     45         if t == 0:
     46             n = self.data_producer.trajectory_length(itraj, stride=stride)
---> 47             self.dtrajs.append(np.empty(n, dtype=int))
     48 
     49         L = np.shape(X)[0]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in dtrajs(self)
     29     def dtrajs(self):
     30         if (len(self._dtrajs) == 0):  # nothing assigned yet, doing that now
---> 31             return self.assign(stride = 1)
     32         else:
     33             return self._dtrajs  # returning what we have saved

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in assign(self, X, stride)
     80         if X is None:
     81             # map to column vectors
---> 82             mapped = self.get_output(stride=stride)
     83             # flatten and save
     84             self._dtrajs = [np.transpose(m)[0] for m in mapped]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in get_output(self, dimensions, stride)
    523         last_itraj = -1
    524         t = 0  # first time point
--> 525         for itraj, chunk in self.iterator(stride=stride):
    526             if itraj != last_itraj:
    527                 last_itraj = itraj

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in iterator(self, stride, lag)
    455             data.
    456         """
--> 457         self._reset(stride=stride)
    458         return TransformerIterator(self, stride=stride, lag=lag)
    459 

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in _reset(self, stride)
    345         """_reset data position"""
    346         if not self._parametrized:  # TODO: should this stay or should it go?
--> 347             self.parametrize()
    348         self._itraj = 0
    349         self._t = 0

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in parametrize(self, stride)
    234                     # first chunk
    235                     return_value = self._param_add_data(
--> 236                         X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y=Y, stride=stride)
    237                     if isinstance(return_value, tuple):
    238                         add_data_finished, lag = return_value

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/assign.pyc in _param_add_data(self, X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y, stride)
     45         if t == 0:
     46             n = self.data_producer.trajectory_length(itraj, stride=stride)
---> 47             self.dtrajs.append(np.empty(n, dtype=int))
     48 
     49         L = np.shape(X)[0]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in dtrajs(self)
     29     def dtrajs(self):
     30         if (len(self._dtrajs) == 0):  # nothing assigned yet, doing that now
---> 31             return self.assign(stride = 1)
     32         else:
     33             return self._dtrajs  # returning what we have saved

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in assign(self, X, stride)
     80         if X is None:
     81             # map to column vectors
---> 82             mapped = self.get_output(stride=stride)
     83             # flatten and save
     84             self._dtrajs = [np.transpose(m)[0] for m in mapped]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in get_output(self, dimensions, stride)
    523         last_itraj = -1
    524         t = 0  # first time point
--> 525         for itraj, chunk in self.iterator(stride=stride):
    526             if itraj != last_itraj:
    527                 last_itraj = itraj

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in iterator(self, stride, lag)
    455             data.
    456         """
--> 457         self._reset(stride=stride)
    458         return TransformerIterator(self, stride=stride, lag=lag)
    459 

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in _reset(self, stride)
    345         """_reset data position"""
    346         if not self._parametrized:  # TODO: should this stay or should it go?
--> 347             self.parametrize()
    348         self._itraj = 0
    349         self._t = 0

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in parametrize(self, stride)
    234                     # first chunk
    235                     return_value = self._param_add_data(
--> 236                         X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y=Y, stride=stride)
    237                     if isinstance(return_value, tuple):
    238                         add_data_finished, lag = return_value

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/assign.pyc in _param_add_data(self, X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y, stride)
     45         if t == 0:
     46             n = self.data_producer.trajectory_length(itraj, stride=stride)
---> 47             self.dtrajs.append(np.empty(n, dtype=int))
     48 
     49         L = np.shape(X)[0]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in dtrajs(self)
     29     def dtrajs(self):
     30         if (len(self._dtrajs) == 0):  # nothing assigned yet, doing that now
---> 31             return self.assign(stride = 1)
     32         else:
     33             return self._dtrajs  # returning what we have saved

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in assign(self, X, stride)
     80         if X is None:
     81             # map to column vectors
---> 82             mapped = self.get_output(stride=stride)
     83             # flatten and save
     84             self._dtrajs = [np.transpose(m)[0] for m in mapped]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in get_output(self, dimensions, stride)
    523         last_itraj = -1
    524         t = 0  # first time point
--> 525         for itraj, chunk in self.iterator(stride=stride):
    526             if itraj != last_itraj:
    527                 last_itraj = itraj

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in iterator(self, stride, lag)
    455             data.
    456         """
--> 457         self._reset(stride=stride)
    458         return TransformerIterator(self, stride=stride, lag=lag)
    459 

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in _reset(self, stride)
    345         """_reset data position"""
    346         if not self._parametrized:  # TODO: should this stay or should it go?
--> 347             self.parametrize()
    348         self._itraj = 0
    349         self._t = 0

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in parametrize(self, stride)
    234                     # first chunk
    235                     return_value = self._param_add_data(
--> 236                         X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y=Y, stride=stride)
    237                     if isinstance(return_value, tuple):
    238                         add_data_finished, lag = return_value

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/assign.pyc in _param_add_data(self, X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y, stride)
     45         if t == 0:
     46             n = self.data_producer.trajectory_length(itraj, stride=stride)
---> 47             self.dtrajs.append(np.empty(n, dtype=int))
     48 
     49         L = np.shape(X)[0]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in dtrajs(self)
     29     def dtrajs(self):
     30         if (len(self._dtrajs) == 0):  # nothing assigned yet, doing that now
---> 31             return self.assign(stride = 1)
     32         else:
     33             return self._dtrajs  # returning what we have saved

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in assign(self, X, stride)
     80         if X is None:
     81             # map to column vectors
---> 82             mapped = self.get_output(stride=stride)
     83             # flatten and save
     84             self._dtrajs = [np.transpose(m)[0] for m in mapped]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in get_output(self, dimensions, stride)
    523         last_itraj = -1
    524         t = 0  # first time point
--> 525         for itraj, chunk in self.iterator(stride=stride):
    526             if itraj != last_itraj:
    527                 last_itraj = itraj

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in iterator(self, stride, lag)
    455             data.
    456         """
--> 457         self._reset(stride=stride)
    458         return TransformerIterator(self, stride=stride, lag=lag)
    459 

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in _reset(self, stride)
    345         """_reset data position"""
    346         if not self._parametrized:  # TODO: should this stay or should it go?
--> 347             self.parametrize()
    348         self._itraj = 0
    349         self._t = 0

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in parametrize(self, stride)
    234                     # first chunk
    235                     return_value = self._param_add_data(
--> 236                         X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y=Y, stride=stride)
    237                     if isinstance(return_value, tuple):
    238                         add_data_finished, lag = return_value

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/assign.pyc in _param_add_data(self, X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y, stride)
     45         if t == 0:
     46             n = self.data_producer.trajectory_length(itraj, stride=stride)
---> 47             self.dtrajs.append(np.empty(n, dtype=int))
     48 
     49         L = np.shape(X)[0]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in dtrajs(self)
     29     def dtrajs(self):
     30         if (len(self._dtrajs) == 0):  # nothing assigned yet, doing that now
---> 31             return self.assign(stride = 1)
     32         else:
     33             return self._dtrajs  # returning what we have saved

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in assign(self, X, stride)
     80         if X is None:
     81             # map to column vectors
---> 82             mapped = self.get_output(stride=stride)
     83             # flatten and save
     84             self._dtrajs = [np.transpose(m)[0] for m in mapped]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in get_output(self, dimensions, stride)
    523         last_itraj = -1
    524         t = 0  # first time point
--> 525         for itraj, chunk in self.iterator(stride=stride):
    526             if itraj != last_itraj:
    527                 last_itraj = itraj

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in iterator(self, stride, lag)
    455             data.
    456         """
--> 457         self._reset(stride=stride)
    458         return TransformerIterator(self, stride=stride, lag=lag)
    459 

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in _reset(self, stride)
    345         """_reset data position"""
    346         if not self._parametrized:  # TODO: should this stay or should it go?
--> 347             self.parametrize()
    348         self._itraj = 0
    349         self._t = 0

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in parametrize(self, stride)
    234                     # first chunk
    235                     return_value = self._param_add_data(
--> 236                         X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y=Y, stride=stride)
    237                     if isinstance(return_value, tuple):
    238                         add_data_finished, lag = return_value

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/assign.pyc in _param_add_data(self, X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y, stride)
     45         if t == 0:
     46             n = self.data_producer.trajectory_length(itraj, stride=stride)
---> 47             self.dtrajs.append(np.empty(n, dtype=int))
     48 
     49         L = np.shape(X)[0]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in dtrajs(self)
     29     def dtrajs(self):
     30         if (len(self._dtrajs) == 0):  # nothing assigned yet, doing that now
---> 31             return self.assign(stride = 1)
     32         else:
     33             return self._dtrajs  # returning what we have saved

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in assign(self, X, stride)
     80         if X is None:
     81             # map to column vectors
---> 82             mapped = self.get_output(stride=stride)
     83             # flatten and save
     84             self._dtrajs = [np.transpose(m)[0] for m in mapped]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in get_output(self, dimensions, stride)
    523         last_itraj = -1
    524         t = 0  # first time point
--> 525         for itraj, chunk in self.iterator(stride=stride):
    526             if itraj != last_itraj:
    527                 last_itraj = itraj

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in iterator(self, stride, lag)
    455             data.
    456         """
--> 457         self._reset(stride=stride)
    458         return TransformerIterator(self, stride=stride, lag=lag)
    459 

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in _reset(self, stride)
    345         """_reset data position"""
    346         if not self._parametrized:  # TODO: should this stay or should it go?
--> 347             self.parametrize()
    348         self._itraj = 0
    349         self._t = 0

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in parametrize(self, stride)
    234                     # first chunk
    235                     return_value = self._param_add_data(
--> 236                         X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y=Y, stride=stride)
    237                     if isinstance(return_value, tuple):
    238                         add_data_finished, lag = return_value

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/assign.pyc in _param_add_data(self, X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y, stride)
     45         if t == 0:
     46             n = self.data_producer.trajectory_length(itraj, stride=stride)
---> 47             self.dtrajs.append(np.empty(n, dtype=int))
     48 
     49         L = np.shape(X)[0]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in dtrajs(self)
     29     def dtrajs(self):
     30         if (len(self._dtrajs) == 0):  # nothing assigned yet, doing that now
---> 31             return self.assign(stride = 1)
     32         else:
     33             return self._dtrajs  # returning what we have saved

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in assign(self, X, stride)
     80         if X is None:
     81             # map to column vectors
---> 82             mapped = self.get_output(stride=stride)
     83             # flatten and save
     84             self._dtrajs = [np.transpose(m)[0] for m in mapped]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in get_output(self, dimensions, stride)
    523         last_itraj = -1
    524         t = 0  # first time point
--> 525         for itraj, chunk in self.iterator(stride=stride):
    526             if itraj != last_itraj:
    527                 last_itraj = itraj

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in iterator(self, stride, lag)
    455             data.
    456         """
--> 457         self._reset(stride=stride)
    458         return TransformerIterator(self, stride=stride, lag=lag)
    459 

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in _reset(self, stride)
    345         """_reset data position"""
    346         if not self._parametrized:  # TODO: should this stay or should it go?
--> 347             self.parametrize()
    348         self._itraj = 0
    349         self._t = 0

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in parametrize(self, stride)
    234                     # first chunk
    235                     return_value = self._param_add_data(
--> 236                         X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y=Y, stride=stride)
    237                     if isinstance(return_value, tuple):
    238                         add_data_finished, lag = return_value

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/assign.pyc in _param_add_data(self, X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y, stride)
     45         if t == 0:
     46             n = self.data_producer.trajectory_length(itraj, stride=stride)
---> 47             self.dtrajs.append(np.empty(n, dtype=int))
     48 
     49         L = np.shape(X)[0]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in dtrajs(self)
     29     def dtrajs(self):
     30         if (len(self._dtrajs) == 0):  # nothing assigned yet, doing that now
---> 31             return self.assign(stride = 1)
     32         else:
     33             return self._dtrajs  # returning what we have saved

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/interface.pyc in assign(self, X, stride)
     80         if X is None:
     81             # map to column vectors
---> 82             mapped = self.get_output(stride=stride)
     83             # flatten and save
     84             self._dtrajs = [np.transpose(m)[0] for m in mapped]

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in get_output(self, dimensions, stride)
    523         last_itraj = -1
    524         t = 0  # first time point
--> 525         for itraj, chunk in self.iterator(stride=stride):
    526             if itraj != last_itraj:
    527                 last_itraj = itraj

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in iterator(self, stride, lag)
    455             data.
    456         """
--> 457         self._reset(stride=stride)
    458         return TransformerIterator(self, stride=stride, lag=lag)
    459 

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in _reset(self, stride)
    345         """_reset data position"""
    346         if not self._parametrized:  # TODO: should this stay or should it go?
--> 347             self.parametrize()
    348         self._itraj = 0
    349         self._t = 0

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in parametrize(self, stride)
    234                     # first chunk
    235                     return_value = self._param_add_data(
--> 236                         X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y=Y, stride=stride)
    237                     if isinstance(return_value, tuple):
    238                         add_data_finished, lag = return_value

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/assign.pyc in _param_add_data(self, X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y, stride)
     45         if t == 0:
     46             n = self.data_producer.trajectory_length(itraj, stride=stride)
---> 47
```

**Comment by marscher** [comment]
this is caused by Transformer._reset(), which calls _parameterize, if
the Transformer is not yet parametrized. We introduced this to enable
transparent re-parametrization.

A fix would either be to add an empty reset method in
AssignClusterCenters or to avoid triggering parametrization. I suggest
using the first option, since we already rely on the behavior during
pipeline operations.

**Comment by franknoe** [comment]
First option is better because it only affects AssignClusterCenters. Go 
ahead.

Big PR coming up. Mostly tests and cosmetics...

Am 13/04/15 um 00:36 schrieb Martin K. Scherer:
> this is caused by Transformer._reset(), which calls _parameterize, if
> the Transformer is not yet parametrized. We introduced this to enable
> transparent re-parametrization.
>
> A fix would either be to add an empty reset method in
> AssignClusterCenters or to avoid triggering parametrization. I suggest
> using the first option, since we already rely on the behavior during
> pipeline operations.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/230#issuecomment-92145156>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
The underlying issue is actually that a method is being called during parametrization which it selfs assumes that the transformer has been parametrized.

The error was that in assign.py the property has been assigned, which triggers a new parameterization. Very confusing - but its fixed now by not accessing the property. 

Avoids changing something critical in parent classes.

**Comment by franknoe** [comment]
Actually that makes a lot of sense. For the future we can think about 
immutable transforms that are always parametrized.

Am 13/04/15 um 13:46 schrieb Martin K. Scherer:
>
> The underlying issue is actually that a method is being called during 
> parametrization which it selfs assumes that the transformer has been 
> parametrized.
>
> The error was that in assign.py the property has been assigned, which 
> triggers a new parameterization. Very confusing - but its fixed now by 
> not accessing the property.
>
> Avoids changing something critical in parent classes.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/230#issuecomment-92324415>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
Still doesn't work for me. I wrote the test in this branch:
    test_assign
please check out and try to get working. The type of error occurs right in the beginning as:
    ValueError: Could not convert "centers" to two-dimensional C-contiguous behaved ndarray of float (32).

**Comment by marscher** [comment]
After fixing one issue now this arises. Please delete your local test_assign branch and repull from master:

git branch -D test_assign
git checkout origin/test_assign -b test_assign

I do not understand why this is failing.

======================================================================
FAIL: test_dtrajs (__main__.TestCluster)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pyemma/coordinates/tests/test_assign.py", line 80, in test_dtrajs
    assert c.dtrajs[0][i] == (i // self.nsample), c.dtrajs[0][i]
AssertionError: 2

**Comment by franknoe** [comment]
OK, that might be. I could not run them because the setupCls was failing 
already.

Am 13/04/15 um 20:59 schrieb Martin K. Scherer:
>
> After fixing one issue now this arises. Please delete your local 
> test_assign branch and repull from master:
>
> git branch -D test_assign
> git checkout origin/test_assign -b test_assign
>
> I do not understand why this is failing.
>
>
>     FAIL: test_dtrajs (*main*.TestCluster)
>
> Traceback (most recent call last):
> File "pyemma/coordinates/tests/test_assign.py", line 80, in test_dtrajs
> assert c.dtrajs[0][i] == (i // self.nsample), c.dtrajs[0][i]
> AssertionError: 2
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/230#issuecomment-92461141>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
fixed by #242

**Comment by marscher** [comment]
======================================================================
FAIL: test_dtrajs (pyemma.coordinates.tests.test_assign.TestCluster)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marscher/workspace/pyemma/pyemma/coordinates/tests/test_assign.py", line 77, in test_dtrajs
    assert c.dtrajs[0][i] == (i // self.nsample), c.dtrajs[0][i]
AssertionError: 3

**Comment by marscher** [comment]
sorry, this occured on an outdated branch.
